language: node_js
sudo: false
node_js:
  - 10
install:
  - npm install
  - npm install -g codecov
script:
  #- npm test
  #- istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  # - codecov
  - nyc mocha --report lcovonly -- -R spec && codecov
